# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95c9bb1f914db6223da495371ac94116d04b3aed4c0af195301de80c5483145d2ebd91af2dff19dbfe188a9ce9c7fd5d2e443c5d203d3cda54dd36cc1c103f3a

test:
  secret_key_base: a232989b9051f8eeb1b383c85d3802054c4c057ec67b80dbedb1608624a588c008167a59482f0449c69f6a4a4b647c0e4dff576774d034ad8c5e8743ee2d3bbf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
